### ISSUE TITLE
Where to submit typo / suggested fixes?

### ISSUE THREAD

**Issue by onlyphantom** [mark-watson/langchain-book-examples#1]
Hey Mark thanks for writing the book and making it available open-source. I'd like to know how one would go about correcting some typos or formatting inconsistencies in the book? 

Under Basic Usage and Examples, the following should have been formatted as a link in markdown but isn't:
```
[documentation](Langchain Quickstart Guide) 
```

In **Using Zapier Integrations With GMail and Google Calendar**, you mis-spelled "Find" for "Fine" in the following passage:

```

When I set up my Zapier account I set up three Zapier Natural Language Actions:

Gmail: Fine Email
Gmail: Send Email
Google Calendar: Find Event
```

In the README of this repo, the word "purchase" is also mis-spelled:

```
You can pruchase this book on LeanPub and get free updates as new versions are released.
```

**Comment by mark-watson** [comment]
Hello Samuel,

Thanks for the typos report! The book can be read free online https://leanpub.com/langchain/read (or can be purchased)
